version: '3.8'
services:
  simpledungeon-api:
    build: ./simpledungeon-api
    ports:
      - "3080:3000"
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - COGNITO_APP_CLIENT_ID=${COGNITO_APP_CLIENT_ID}
      - COGNITO_APP_CLIENT_SECRET=${COGNITO_APP_CLIENT_SECRET}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  simpledungeon-app:
    build: ./simpledungeon-app
    ports:
      - "3000:3000"
